# logging config
logging:
  config: classpath:logback-spring.xml
  file: ${spring.application.name}  # logback-spring.xml 에서 .log 붙여준다.
---
spring:
  profiles:
    active: local

---
spring:
  profiles: local
  aws:
    s3config:
      clientRegion: "ap-northeast-1"
      bucketName: "poc.online-luxury-market"
      accessKey: ENC(D5Jfwx2R2/8p+KcyhKuhVwk34aMmX/99z1+M+af1Xa4eFGdY8RvZeK38gYcR5slO)
      secretKey: ENC(oodGhHNp1Ukw7/4uauYA5ogdVF3DN14JE84MM8TaJW9WuXFzu7e5vaoyl/Fi2WKBrtTt12cqP95PyyObRgosQ9FPR3fHs8b8)
      folderName: "blockchain"
      fileFormat: "png"
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: jdbc:mysql://poc-cluster.cluster-cytgq1fzvvht.ap-northeast-2.rds.amazonaws.com:3306/HOMEPAGE?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: "devtemco"
    password: ENC(oMYEgzh8XSin/OnlnRDMIQyTOkYcDVZvSlvXucf5FM8c+tyTNeRi4A==)
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: datastorage
  private-key: "p05pWLrQ3Ms6ePYnkHmZM1WdWwvjq0m/RG2/Dd/UjGxcKIlRYN7cY3FeYPT2wgnjRSfGD6ttq+RuDDJbsz1FXmFu9zM1LOQ2MfYp7JPB20Y="
  contract-address: "0x85bf8380efb2f1154c58f83cf18dbc7f36617a5a"
  chain-url: "https://public-node.testnet.rsk.co:443"
  thymeleaf:
    cache: false


jasypt:
  encryptor:
   bean: jasyptStringEncrptor