spring:
#  aws:
#    s3config:
#      clientRegion: "ap-northeast-1"
#      bucketName: "poc.online-luxury-market"
#      accessKey: ENC(D5Jfwx2R2/8p+KcyhKuhVwk34aMmX/99z1+M+af1Xa4eFGdY8RvZeK38gYcR5slO)
#      secretKey: ENC(oodGhHNp1Ukw7/4uauYA5ogdVF3DN14JE84MM8TaJW9WuXFzu7e5vaoyl/Fi2WKBrtTt12cqP95PyyObRgosQ9FPR3fHs8b8)
#      folderName: "blockchain"
#      fileFormat: "png"
  datasource:
    url: jdbc:mysql://guhada-dev-cluster.cluster-ro-cytgq1fzvvht.ap-northeast-2.rds.amazonaws.com:3306/guhada_dev?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: api-order
    password: ENC(N6M89ZHmfkOM1+FBaNpeVx2e/9YyJxaR)
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect : io.temco.guhada.user.config.InnoDBDialect
  application:
    name: datastorage
  thymeleaf:
    cache: false

logging:
  service: blockchain

jasypt:
  encryptor:
   bean: jasyptStringEncrptor

cloud:
  uploader: awsUploader
  domain: https://d3ikprf0m31yc7.cloudfront.net/

smart-contract:
  chain-url: "https://ropsten.infura.io/v3/67b3ebcb7a574122967fb41c7a968b90"
  guhada-token-contract : '0xA8F52BE91F0229CB21e16111C7a8ea2b48b243f9'
  payer-private-key : ENC(bqj2JO39Jmep+4NTbPRlUM+7x2E9UjJcgoP5aTSwUscUzzlwjHl5K7mq5pIG5qmXBa6Xr7xnN3Imf2er2A8oGekBXUUOhOKvQM0vzBjxbw4=)
  payer-public-key : '0x08260736c18bd8612bee2b21beedf4e97c0bc6b9'
  sender-private-key : ENC(hIARKjhXzxrzXpTi149W7U+TbLqpb3DX/RTLMf6dd/FOHoCYBC/P9KMdS+gdvLxpuD19cG2icQCMAOJ4GycltX3Zyg/ZVmrjI7vm44WCj4E=)
  sender-public-key : '0xc45bddbd8f5c74ef239cb345dab43a9b9bf6cd19'
  delegation-contract : '0x2e160a2b643c630e540243725764112f1bfdb1b3'
  lucky-draw-contract : '0xa61Acf1443B2684B4ec71185C9d94Ed106d1eBAB'
  track-record-contract : '0x265C378E636c44d7F49f0415eb2c48152e276046'
  guhada-account: ENC('jDMMBySGK55pChp0mEm3yLYRgofadq4pQLBmaWuCgBEIk4tleRqzJdZeCg0b7OZQT39z+FZBst9dhLxuaUSkDFrVkh+pav8Zksd1Eun11Vc=')

server:
  port: 8080
  host: 127.0.0.1:8080

retrofit:
  benefit-api: 'http://dev.benefit.guhada.com'
  product-api: 'http://dev.product.guhada.com'

cron:
  exp:
    blockchain:
      upload-deal : 0 1 1 1 1 ?
      guhada-airdrop-update : 0 0 12 * * ?
      coinone-guhada-airdrop-update : 0 0 0 * * ?
      track-record-upload-blockchain : 0 0/1 * * * ?