spring:
#  aws:
#    s3config:
#      clientRegion: "ap-northeast-1"
#      bucketName: "poc.online-luxury-market"
#      accessKey: ENC(D5Jfwx2R2/8p+KcyhKuhVwk34aMmX/99z1+M+af1Xa4eFGdY8RvZeK38gYcR5slO)
#      secretKey: ENC(oodGhHNp1Ukw7/4uauYA5ogdVF3DN14JE84MM8TaJW9WuXFzu7e5vaoyl/Fi2WKBrtTt12cqP95PyyObRgosQ9FPR3fHs8b8)
#      folderName: "blockchain"
#      fileFormat: "png"
  datasource:
    url: jdbc:mysql://guhada-dev-cluster.cluster-ro-cytgq1fzvvht.ap-northeast-2.rds.amazonaws.com:3306/guhada_qa?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: api-order
    password: ENC(N6M89ZHmfkOM1+FBaNpeVx2e/9YyJxaR)
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect : io.temco.guhada.user.config.InnoDBDialect
  application:
    name: datastorage
  thymeleaf:
    cache: false

logging:
  service: blockchain

jasypt:
  encryptor:
   bean: jasyptStringEncrptor

cloud:
  uploader: awsUploader
  domain: https://d3ikprf0m31yc7.cloudfront.net/

smart-contract:
  chain-url: "https://ropsten.infura.io/v3/67b3ebcb7a574122967fb41c7a968b90"
  guhada-token-contract : '0x2fc246aa66f0da5bb1368f688548ecbbe9bdee5d'
  payer-private-key : ENC('L8TXJDMuM01pshEeoqTo8lBYjipe4PyWsk8xsTbIbuIzIes6MUw5NX9Nxbjmj3fOEnQ8W8LqTZnTkMa7086QDIkd5hLChGHtamRXf8Y8l0OBoRvlSIhKjA9nibRAOkcnO3fDq9kHEx9mShz6Xwx/5+Nn1pKNZSRdWSRxiyC8Gzg=')
  payer-public-key : '0xe7223e5e41186a782e4a1f709829f521f43b18e5'
  sender-private-key : ENC('36ae62rlYJFJBxhxP8tbj3dAMzC4/4WQH3Zz7P6N6pe05xNFqNSQg2OxA/wY0xnpH0eavkGGAPP2CMwxCdT+fP9TNWnH44l9irFGrRgQ8cE=')
  sender-public-key : '0xbb1da7aa9ea4005298f28a2e9579e412a856a5ff'
  delegation-contract : '0x2e160a2b643c630e540243725764112f1bfdb1b3'
  lucky-draw-contract : '0x11d88F9940cBC0c4238b61ADF401b242Fd5514eE'
  track-record-contract : '0x35AE79fDFF6586b2aed65CC3ddA810b418A21653'
  guhada-account: ENC('jDMMBySGK55pChp0mEm3yLYRgofadq4pQLBmaWuCgBEIk4tleRqzJdZeCg0b7OZQT39z+FZBst9dhLxuaUSkDFrVkh+pav8Zksd1Eun11Vc=')
  kestore-decryption : ENC('XEgIk3wLNhetw+0KOEHtt82EZBEelhBq')

server:
  port: 8080
  host: qa.blockchain.guhada.com

retrofit:
  benefit-api: 'http://qa.benefit.guhada.com'
  product-api: 'http://qa.product.guhada.com'

cron:
  exp:
    blockchain:
      upload-deal : 0 * 3-6 * * ?
      guhada-airdrop-update : 0 0 12 * * ?
      coinone-guhada-airdrop-update : 0 0 0 * * ?
      track-record-upload-blockchain : 0 0 12  * * ?