# logging config
logging:
  config: classpath:logback-spring.xml
  file: ${spring.application.name}  # logback-spring.xml 에서 .log 붙여준다.
---
spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: jdbc:mysql://poc-cluster.cluster-cytgq1fzvvht.ap-northeast-2.rds.amazonaws.com:3306/HOMEPAGE?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: "devtemco"
    password: "devTemco88!"
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: datastorage
  private-key: "p05pWLrQ3Ms6ePYnkHmZM1WdWwvjq0m/RG2/Dd/UjGxcKIlRYN7cY3FeYPT2wgnjRSfGD6ttq+RuDDJbsz1FXmFu9zM1LOQ2MfYp7JPB20Y="
  contract-address: "0x41f41b121b5e04b66bb6143a412bce731adca0e7"
  chain-url: "https://public-node.testnet.rsk.co:443"
  thymeleaf:
    cache: false