spring:
#  aws:
#    s3config:
#      clientRegion: "ap-northeast-1"
#      bucketName: "poc.online-luxury-market"
#      accessKey: ENC(D5Jfwx2R2/8p+KcyhKuhVwk34aMmX/99z1+M+af1Xa4eFGdY8RvZeK38gYcR5slO)
#      secretKey: ENC(oodGhHNp1Ukw7/4uauYA5ogdVF3DN14JE84MM8TaJW9WuXFzu7e5vaoyl/Fi2WKBrtTt12cqP95PyyObRgosQ9FPR3fHs8b8)
#      folderName: "blockchain"
#      fileFormat: "png"
  datasource:
    url: jdbc:mysql://guhada-prod.cytgq1fzvvht.ap-northeast-2.rds.amazonaws.com:3306/guhada_prod?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: api-order
    password: ENC(N6M89ZHmfkOM1+FBaNpeVx2e/9YyJxaR)
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect : io.temco.guhada.user.config.InnoDBDialect
  application:
    name: datastorage
  thymeleaf:
    cache: false

logging:
  service: blockchain

jasypt:
  encryptor:
   bean: jasyptStringEncrptor

cloud:
  uploader: awsUploader
  domain: https://d3ikprf0m31yc7.cloudfront.net/

smart-contract:
  chain-url: "https://mainnet.infura.io/v3/67b3ebcb7a574122967fb41c7a968b90"
  guhada-token-contract : '0x0DAc5c5F8438Bf2a02ee68ba87e0878d19b45bD9'
  payer-private-key : ENC(bqj2JO39Jmep+4NTbPRlUM+7x2E9UjJcgoP5aTSwUscUzzlwjHl5K7mq5pIG5qmXBa6Xr7xnN3Imf2er2A8oGekBXUUOhOKvQM0vzBjxbw4=)
  payer-public-key : '0x08260736c18bd8612bee2b21beedf4e97c0bc6b9'
  sender-private-key : ENC(hIARKjhXzxrzXpTi149W7U+TbLqpb3DX/RTLMf6dd/FOHoCYBC/P9KMdS+gdvLxpuD19cG2icQCMAOJ4GycltX3Zyg/ZVmrjI7vm44WCj4E=)
  sender-public-key : '0xc45bddbd8f5c74ef239cb345dab43a9b9bf6cd19'
  delegation-contract : '0x2e160a2b643c630e540243725764112f1bfdb1b3'
  lucky-draw-contract : '0x11d88F9940cBC0c4238b61ADF401b242Fd5514eE'

server:
  port: 8080
  host: blockchain.guhada.com

retrofit:
  benefit-api: 'https://benefit.guhada.com'

cron:
  exp:
    blockchain:
      upload-deal : 0 * 3-6 * * ?
      guhada-airdrop-update : 0 0 12 * * ?